baseURL: "https://emilyryu.github.io/" 
title: Emily Ryu
pagination:
    pagerSize: 20
# theme: PaperMod
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Contact
          url: contact/
          weight: 3

params:
    description: "I'm a rising fifth-year PhD student in Computer Science at Cornell University, advised by Éva Tardos and Jon Kleinberg. My research interests span algorithmic game theory, mechanism design, and optimization, particularly with more realistic models of human behavior, cognition, and learning."
    author: Emily Ryu
    googleAnalyticsID: "G-DEFBS2HYP7"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","teaching","contact"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Emily Ryu
          subtitle: PhD student in Computer Science at Cornell University.
          # subtitle: "Hello! I'm a rising fifth-year PhD student in Computer Science at Cornell University. I'm very fortunate to be advised by [**Prof. Éva Tardos**](https://www.cs.cornell.edu/~eva/) and [**Prof. Jon Kleinberg**](https://www.cs.cornell.edu/home/kleinber/), and be supported by the [**NSF GRFP**](https://www.nsfgrfp.org/). My research interests span algorithmic game theory, mechanism design, learning theory, and optimization, particularly with more realistic models of behavioral and cognitive constraints. Recently, I've been thinking about matching markets with biased and malleable preferences.	  
#<br><br>
# Previously, I graduated from Princeton University with an A.B. in Chemistry and minors in Applied Math and Computer Science, where I worked with [**Prof. Matt Weinberg**](https://www.cs.princeton.edu/~smattw/) on Bayesian auction design for multi-item revenue maximization.
# <br><br>
# Non-academic interests (many starting with a C and supported by images): [**caffeine**](/coffee.jpg), [**cats**](/pokki.jpg), [**colouring-of-hair**](/colouring.jpg), [**crafting**](https://www.instagram.com/egg.t.arts/), dance, yoga"
          imageUrl: "avatar.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: eryu_headshot
          buttons:
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: CV (updated July 2025)
              url: "/CV_eryu.pdf"

    socialIcons:
        - name: Email
          url: contact/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=5OdxkNEAAAAJ


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Emily Ryu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2